# Generated by Django 4.1.2 on 2022-10-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chainbreakers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='field',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
        migrations.AddField(
            model_name='profile',
            name='fiat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Unknown', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='quant',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quant', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chainbreakers.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant1', models.IntegerField(default=0)),
                ('buy', models.BooleanField()),
                ('price', models.FloatField(default=0)),
                ('type', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chainbreakers.profile')),
            ],
        ),
    ]
