# Generated by Django 4.1.2 on 2022-10-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chainbreakers', '0003_transaction_seller_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='type',
            new_name='market',
        ),
    ]
